[package]
name = "ruff_index"
version = "0.0.0"
publish = false
edition = "2021"

[lib]

[dependencies]
ruff_macros = { path = "../ruff_macros" }
serde = { workspace = true, optional = true }

[dev-dependencies]
static_assertions = "1.1.0"

[features]
serde = ["dep:serde"]
